services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest-alpine
    ports:
      - 8123:8123
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
