services:
  clickhouse:
    image: clickhouse/clickhouse-server:head
    ports:
      - 8123:8123
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ch_data:/var/lib/clickhouse
      - ch_logs:/var/log/clickhouse-server

volumes:
  ch_data:
  ch_logs:
